---
# This Playbook adds and updates users!

- hosts: all

  remote_user: root
  become: true
  become_user: root
  tags: users
  vars_files:
  - vars/main.yml
  handlers:
  - include: handlers/main.yml

  tasks:
  - include: tasks/users_creation.yml
  - include: tasks/users_sudo.yml
  - include: tasks/users_ssh.yml
