---
# ===============================================================
# users: Access, security and permissions
# ===============================================================

- include_vars: "defaults/main.yml"

- name: Adding the groups
  group:
    name={{ item }}
    state=present
  with_items: "{{ ansible_role_users.groups }}"
  tags: users_creation

- name: Adding root into our groups
  user:
    name=root
    groups={{ ansible_role_users.user_groups }}
  tags: users_creation

- name: Creating the user(s)
  user:
    name={{ item }}
    shell=/bin/bash group={{ ansible_role_users.user_group }}
    groups={{ ansible_role_users.user_groups }}
    createhome=yes
  with_items: "{{ ansible_role_users.users }}"
  tags: users_creation

- name: Registering the public key against users
  authorized_key:
    user={{ item }}
    key="{{ lookup('file', '{{ ansible_role_users.public_key }}') }}"
  with_items: "{{ ansible_role_users.users }}"
  tags: users_creation

- name: Ensure the user group has access to /var/www
  file:
    path=/var/www
    state=directory
    owner=www-data
    group={{ ansible_role_users.user_group }}
    mode=0775
